### ISSUE TITLE
Provide a way for the person providing their QR code to be able to verify that they are being scanned by the genuine, unmodified version of this application

### ISSUE THREAD

**Issue by edandersen** [nhsx/covid-pass-verifier#6]
It is possible to modify this application and deploy it to devices, maintaining full NHS branding, with additional functionality to send the scanned person's personal information including first, last name, date of birth and health information to third parties including insurance companies, credit reference agencies, employer databases etc.

There is no way for the person providing their QR code to know that this is not happening.

There must be a way for the person providing their personal information via unencrypted QR code to be able to verify that this is not occuring and the app that is being used is the genuine app store provided version without modifications. The UX of this must make it possible to perform this verification in a nightclub queue without physical access to the scanning device.

**Comment by edandersen** [comment]
Closing as designed.

Workaround is not to provide your QR code.

**Comment by cl0udl1ne** [comment]
Can we get any more clarification on "Workaround is not to provide your QR code"? And the reason for this issue's original text and title being removed?

Does this mean it is not possible to enter any venue or event requiring covid pass verification if you do not wish to be exposed to this potential vulnerability?

Is it possible to avoid with a 'vaccination pass letter', or do they also work via a QR code that is scanned by this application?

**Comment by edandersen** [comment]
@cl0udl1ne The title and description have been removed because this is appears to be part of the design and I don't want this issue indexed on search engines.

The QR codes are not encrypted, therefore:

- Anybody can scan them and read your unverified first name, last name, DOB and vaccination status.
- They can be scanned without any audit trail, measurement of usage, retraction of permission to scan etc.
- You can build a fake NHS branded app today that will scan codes, optionally verify them and send the personal information off somewhere else
- You can build a fake NHS branded app today that shows the user's first, last names, date of birth and vaccination dates/status on the screen WITHOUT verifying this information
- The NHS publishes the public keys used to sign the QR code data, so anybody today can "verify" that a QR code is valid and has been issued by the NHS. The NHS has now published and continues to publish the public keys to verify these codes where you can now build an entirely offline (apart from getting new keys once every 24 hours) scanner and embed in any system - you can build a door entry system that requires NHS-signed proof of vaccination today.

The problem here is that anybody can do this. If the content of the codes were encrypted, at least the NHS could provide a properly controlled API to verify vaccination status (and vaccination status only, not exposing personal information), including the ability to revoke API permission if the system is being abused. Whilst this system will work offline as designed, it is overwhelmingly open to fraud and abuse, including possibly facilitating illegal discrimination in my opinion. It could be being used today but we wouldn't know and there would be no way of finding out.

The NHS letters have the same QR codes on so they are not a workaround. The only workaround is to not provide your QR code to anybody.
